[package]
name = "cortex_r5_emul"
version = "0.1.0"
edition = "2024"

[dependencies]
semihosting = { version = "0.1", features = ["stdio"] }
panic-halt = "1.0"            # or panic-itimer, panic-semihosting, etc.
aarch32-rt = "0.3.0"
aarch32-cpu = "0.3.0"
portable-atomic = "1.13.1"

[build-dependencies]
arm-targets = "0.4.2"