[package]
name = "qemu_be_error"
version = "0.1.0"
edition = "2021" # here 2021 works

[dependencies]
semihosting = { version = "0.1", features = ["stdio", "trap-hlt"] }
panic-halt = "1.0"
aarch32-rt = "0.3.0"
aarch32-cpu = "0.3.0"
portable-atomic = "1.13.1"

[build-dependencies]
arm-targets = "0.4.2"