[build]
target = "armebv7r-none-eabi"
# built specifically for the Armv7-R profile (Cortex‑R family) in big‑endian mode
# targeted at Cortex‑R4/5/7/8 (big‑endian, no OS).
# It’s built for one architecture family + profile + endianness: Armv7‑R, big‑endian, bare‑metal


[target.armv7r-none-eabi]
runner = "qemu-system-arm -machine versatileab -cpu cortex-r5 -semihosting -nographic -audio none -kernel"

[target.armebv7r-none-eabi]
linker = "/home/nielsouvrard/gcc-linaro-7.5.0-2019.12-x86_64_armeb-eabi/bin/armeb-eabi-gcc"
runner = "qemu-system-arm -machine versatileab -cpu cortex-r5 -semihosting -nographic -audio none -kernel"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
debug = 0
