[build]
target = "armebv7r-none-eabi"
# built specifically for the Armv7-R profile (Cortex‑R family) in big‑endian mode
# targeted at Cortex‑R4/5/7/8 (big‑endian, no OS).
# It’s built for one architecture family + profile + endianness: Armv7‑R, big‑endian, bare‑metal


[target.armv7r-none-eabi]
# change '-mcpu=cortex-r5' to '-mcpu=cortex-r5f' if you use eabi-fpu feature, otherwise
# qemu-system-arm will lock up
runner = "qemu-system-arm -machine versatileab -cpu cortex-r5 -semihosting -nographic -audio none -kernel"

# [target.armebv7r-none-eabi]
# linker = "rust-lld"
# runner = ["qemu-system-arm", "-M", "versatilepb", "-audio", "none", "-cpu", "cortex-r5", "-nographic", "-nodefaults", "-semihosting", "-d", "guest_errors", "-m", "128M", "-semihosting-config", "enable=on,target=native", "-kernel"]
# rustflags = [
#     "-C", "link-arg=-Tlink.x",
# ]
# runner = "./renode-run.sh"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
debug = 0
